name: "efficio-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: efficio-db
    environment:
      POSTGRES_USER: "ayushpetwal"
      POSTGRES_DB: "efficio"
      POSTGRES_PASSWORD: Ayush<$0009>
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data:
